tasks:
  - name: Install and run dev server
    init: npm install
    command: npm run dev

ports:
  - port: 4000
    onOpen: open-preview

vscode:
  extensions:
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
