version: '3.8'

services:
  omnisocial:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - PORT=4000
    command: npm run dev
