name: 📜 Generate Changelog

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sinceTag: ${{ github.event.before }}
          futureRelease: ${{ github.ref_name }}
          output: docs/releases/CHANGELOG.md

      - name: Commit changelog
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add docs/releases/CHANGELOG.md
          git commit -m "📜 Update changelog for ${{ github.ref_name }}"
          git push
