name: Weekly Digest

on:
  schedule:
    - cron: '0 8 * * MON'  # Every Monday at 08:00 UTC
  workflow_dispatch:

jobs:
  digest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Requests
        run: pip install requests

      - name: Generate Weekly Digest
        run: python3 weekly-digest.py

      - name: Commit Weekly Digest
        run: |
          git config --global user.name 'omni-bot'
          git config --global user.email 'noreply@github.com'
          git add weekly-digest.md
          git commit -m '📬 Weekly Digest update'
          git push
