openapi: 3.0.0
info:
  title: Protocol Hub API
  description: API documentation for Protocol Hub's federated social routes
  version: 1.0.0
servers:
  - url: http://localhost:4000
paths:
  /activitypub:
    get:
      summary: ActivityPub endpoint
      responses:
        '200':
          description: Returns stub message
  /atproto:
    get:
      summary: AT Protocol endpoint
      responses:
        '200':
          description: Returns stub message
  /nostr:
    get:
      summary: Nostr endpoint
      responses:
        '200':
          description: Returns stub message
  /.well-known/webfinger:
    get:
      summary: Webfinger identity resolver
      parameters:
        - in: query
          name: resource
          schema:
            type: string
          required: true
          description: User resource string
      responses:
        '200':
          description: Webfinger response
  /did/{id}:
    get:
      summary: DID Document resolver
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: DID Document JSON
