name: Sync Wiki from wiki-content

on:
  push:
    paths:
      - 'wiki-content/**'
  workflow_dispatch:

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'omni-bot'
          git config --global user.email 'noreply@github.com'

      - name: Give permissions
        run: chmod +x push-wiki.sh

      - name: Push to Wiki
        env:
          GITHUB_SSH_KEY: ${{ secrets.WIKI_PUSH_KEY }}
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "$GITHUB_SSH_KEY"
          ./push-wiki.sh
